### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by aquelefelipe** [aquelefelipe/mandacaru#1]
-  6 itens (quem somos, sobre, equipe, galeria, patrocinadores e contato)

- Logo 

- Se deslocar para seção da página quando clicar no respectivo item 

- deixar de ser transparente quando não estiver no topo da página

**Comment by gabrielaleal** [comment]
Tudo feito, falta só o terceiro tópico (se deslocar para seção da página quando clicar no respectivo item)

**Comment by aquelefelipe** [comment]
Quando colocar o cursor em cima de algum texto da navbar colocar uma mudança de estado como sublinhar o texto, para mostrar que tem alguma ação relacionada a ele

**Comment by FactorMouk** [comment]
Mudança de estado feita.

**Comment by gabrielaleal** [comment]
tudo feito
