### ISSUE TITLE
História

### ISSUE THREAD

**Issue by aquelefelipe** [aquelefelipe/mandacaru#6]
- Linha do tempo com 4 marcos anteriores e o último com o video promocional mais atual

**Comment by FactorMouk** [comment]
Adicionado, faltando apenas pequenos detalhes no design da linha do tempo, responsividade (mudança da orientação da linha do tempo a partir da mudança da resolução) e o vídeo promocional no ultimo marco

**Comment by FactorMouk** [comment]
Aberto a sugestões para a linha do tempo

**Comment by aquelefelipe** [comment]
Esta faltando colocar um texto entra o título e a linha do tempo, eu vou confirmar com eles que texto deve ficar neste lugar

**Comment by FactorMouk** [comment]
Responsividade feita, falta apenas ajuste de pequenos detalhes de proporcionalidade, o texto pré-linha do tempo e o vídeo promocional

**Comment by gabrielaleal** [comment]
feito
