### ISSUE TITLE
Áreas

### ISSUE THREAD

**Issue by aquelefelipe** [aquelefelipe/mandacaru#8]
Descrição de cada área que compõe o projeto atualmente

- Distribuição das área: 4 numa primeira linha, 4 numa segunda e 3 na última.

- Adicionar mais duas áreas além daquelas que estão no documento enviado: Elétrica e PPM

- Ícone de PPM ser uma chave inglesa ou algum tipo de ferramenta

- Ícone de Elétrica ser um raio

- Mudar ícone de estabilidade

**Comment by FactorMouk** [comment]
Feito!
